const masks = `@0-00.usa.cc
@0-mail.com
@001.igg.biz
@027168.com
@0815.ru
@0815.su
@0box.eu
@0clickemail.com
@0mel.com
@0wnd.net
@0wnd.org
@1000rebates.stream
@10mail.com
@10mail.org
@10minut.com.pl
@10minut.xyz
@10minutemail.be
@10minutemail.co.uk
@10minutemail.co.za
@10minutemail.com
@10minutemail.net
@10minutemail.nl
@10minutemail.pro
@10minutemail.us
@10minutemailbox.com
@10minutenemail.de
@10minutesmail.com
@10minutesmail.fr
@10minutmail.pl
@10vpn.info
@11163.com
@12hosting.net
@12minutemail.com
@12storage.com
@14n.co.uk
@15qm.com
@1chuan.com
@1clck2.com
@1fsdfdsfsdf.tk
@1mail.ml
@1usemail.com
@1webmail.info
@2.0-00.usa.cc
@20email.eu
@20mail.eu
@20mail.in
@20mail.it
@20minutemail.com
@20mm.eu
@2120001.net
@21cn.com
@24hourmail.net
@2anom.com
@2ether.net
@2fdgdfgdfgdf.tk
@2odem.com
@2prong.com
@30mail.ir
@30minutemail.com
@30wave.com
@3202.com
@333.igg.biz
@33mail.com
@36ru.com
@3l6.com
@3trtretgfrfe.tk
@4057.com
@418.dk
@42o.org
@4gfdsgfdgfd.tk
@4tb.host
@4warding.net
@55hosting.net
@5ghgfhfghfgh.tk
@5gramos.com
@5july.org
@5oz.ru
@5x25.com
@5ymail.com
@6-6-6.igg.biz
@6-6-6.nut.cc
@6-6-6.usa.cc
@672643.net
@675hosting.com
@6hjgjhgkilkj.tk
@6ip.us
@6paq.com
@7mail.ml
@7tags.com
@80665.com
@99.com
@99experts.com
@9ox.net
@a-bc.net
@a.safe-mail.gq
@a45.in
@a7996.com
@aa5zy64.com
@ab0.igg.biz
@abacuswe.us
@abakiss.com
@abcmail.email
@abilitywe.us
@abnamro.usa.cc
@abovewe.us
@absolutewe.us
@abundantwe.us
@abusemail.de
@abyssmail.com
@academywe.us
@acceleratewe.us
@accentwe.us
@acceptwe.us
@acclaimwe.us
@accordwe.us
@accreditedwe.us
@achievementwe.us
@achievewe.us
@acornwe.us
@acrylicwe.us
@activatewe.us
@activitywe.us
@acuitywe.us
@acumenwe.us
@adaptivewe.us
@adaptwe.us
@adeptwe.us
@adiq.eu
@aditus.info
@admiralwe.us
@adoniswe.us
@advantagewe.us
@advantimo.com
@adventurewe.us
@adventwe.us
@advisorwe.us
@advocatewe.us
@adwaterandstir.com
@aegde.com
@aegia.net
@aegiswe.us
@affiliate-nebenjob.info
@affiliatedwe.us
@affinitywe.us
@affluentwe.us
@affordablewe.us
@afrobacon.com
@afterhourswe.us
@agendawe.us
@agilewe.us
@agorawe.us
@agtx.net
@ahk.jp
@air2token.com
@airsi.de
@ajaxapp.net
@akapost.com
@akerd.com
@akgq701.com
@al-qaeda.us
@albionwe.us
@alchemywe.us
@alfaromeo.igg.biz
@aliaswe.us
@alienware13.com
@aligamel.com
@alisongamel.com
@alivewe.us
@allaccesswe.us
@allamericanwe.us
@allaroundwe.us
@alldirectbuy.com
@allegiancewe.us
@allegrowe.us
@allgoodwe.us
@allinonewe.us
@alloutwe.us
@alloywe.us
@allprowe.us
@allseasonswe.us
@allstarwe.us
@allurewe.us
@almondwe.us
@alph.wtf
@alphaomegawe.us
@alpinewe.us
@altairwe.us
@altitudewe.us
@altuswe.us
@ama-trade.de
@ama-trans.de
@amadeuswe.us
@amail.club
@amail.com
@amail4.me
@amberwe.us
@ambiancewe.us
@ambitiouswe.us
@amelabs.com
@americanawe.us
@americasbestwe.us
@americaswe.us
@amicuswe.us
@amiri.net
@amplewe.us
@amplifiedwe.us
@amplifywe.us
@ampsylike.com
@analogwe.us
@analysiswe.us
@analyticalwe.us
@analyticswe.us
@analyticwe.us
@anappfor.com
@andthen.us
@animesos.com
@ano-mail.net
@anon-mail.de
@anonmails.de
@anonymail.dk
@anonymbox.com
@antichef.com
@antichef.net
@antispam.de
@antispam24.de
@anyalias.com
@aoeuhtns.com
@apfelkorps.de
@aphlog.com
@apkmd.com
@appc.se
@appixie.com
@apps.dj
@armyspy.com
@aron.us
@art-en-ligne.pro
@arurgitu.gq
@arvato-community.de
@asdasd.nl
@asdasd.ru
@asiarap.usa.cc
@asoes.tk
@asorent.com
@astonut.tk
@asu.mx
@asu.su
@audi.igg.biz
@ausgefallen.info
@autorobotica.com
@autotwollow.com
@aver.com
@averdov.com
@avls.pt
@awatum.de
@axon7zte.com
@axsup.net
@azcomputerworks.com
@azmeil.tk
@b1of96u.com
@b2bx.net
@b2cmail.de
@badgerland.eu
@badpotato.tk
@banit.club
@banit.me
@bareed.ws
@barryogorman.com
@bartdevos.be
@bauwerke-online.com
@baxomale.ht.cx
@bbhost.us
@bcaoo.com
@bcast.ws
@bcb.ro
@bccto.me
@bdmuzic.pw
@bearsarefuzzy.com
@beddly.com
@beefmilk.com
@bershka-terim.space
@bestoption25.club
@besttempmail.com
@bestvpn.top
@betr.co
@bgtmail.com
@bgx.ro
@bigstring.com
@binka.me
@binkmail.com
@binnary.com
@bitwhites.top
@bitymails.us
@bladesmail.net
@blan.tech
@blip.ch
@blogmyway.org
@blow-job.nut.cc
@bluedumpling.info
@bluewerks.com
@boatmail.us
@bobmail.info
@bofthew.com
@bonobo.email
@borged.com
@bot.nu
@boun.cr
@boxformail.in
@boximail.com
@boxtemp.com.br
@breakthru.com
@brefmail.com
@brennendesreich.de
@broadbandninja.com
@bsnow.net
@bspamfree.org
@btcmail.pw
@btizet.pl
@bulrushpress.com
@bum.net
@bumpymail.com
@bunchofidiots.com
@bund.us
@burstmail.info
@businesssuccessislifesuccess.com
@buspad.org
@buy003.com
@buymoreplays.com
@byebyemail.com
@byom.de
@cam4you.cc
@camping-grill.info
@candymail.de
@canitta.icu
@car101.pro
@carbtc.net
@cars2.club
@caseedu.tk
@cavi.mx
@cc-cc.usa.cc
@cdpa.cc
@ceed.se
@cek.pm
@cellurl.com
@centermail.net
@cetpass.com
@chacuo.net
@chaichuang.com
@chalupaurybnicku.cz
@chammy.info
@cheaphub.net
@cheatmail.de
@chickenkiller.com
@chielo.com
@chilkat.com
@choco.la
@chogmail.com
@choicemail1.com
@chong-mail.net
@chumpstakingdumps.com
@cigar-auctions.com
@civx.org
@ckiso.com
@clandest.in
@clearwatermail.info
@clgt.wtf
@clickdeal.co
@clipmail.eu
@clrmail.com
@cmail.club
@cmail.net
@cnamed.com
@cnew.ir
@cnmsg.net
@cobarekyo1.ml
@cocovpn.com
@coieo.com
@coldemail.info
@completegolfswing.com
@comwest.de
@consumerriot.com
@contbay.com
@cool.fr.nf
@coolandwacky.us
@coolimpool.org
@coreclip.com
@courriel.fr.nf
@courrieltemporaire.com
@coza.ro
@crapmail.org
@crastination.de
@crazespaces.pw
@crazymailing.com
@cream.pink
@crossroadsmail.com
@crusthost.com
@ctmailing.us
@ctos.ch
@cubiclink.com
@curlhph.tk
@curryworld.de
@cust.in
@cuvox.de
@cyber-innovation.club
@cyber-phone.eu
@d1yun.com
@d3p.dk
@dab.ro
@daemsteam.com
@damnthespam.com
@dandikmail.com
@dataarca.com
@datazo.ca
@datum2.com
@davidkoh.net
@dayrep.com
@dbunker.com
@dbz5mchild.com
@dcemail.com
@ddcrew.com
@de-a.org
@deadchildren.org
@deagot.com
@deekayen.us
@defomail.com
@degradedfun.net
@dengekibunko.gq
@dengekibunko.ml
@der-kombi.de
@derkombi.de
@derluxuswagen.de
@despammed.com
@devnullmail.com
@deyom.com
@dfgh.net
@dhm.ro
@dhy.cc
@dialogus.com
@diapaulpainting.com
@digitalesbusiness.info
@digitalmariachis.com
@digitalsanctuary.com
@dikriemangasu.tk
@disbox.org
@discard.email
@discardmail.com
@discardmail.de
@disign-concept.eu
@disign-revelation.com
@dispomail.eu
@disposable-email.ml
@disposable.ml
@disposableaddress.com
@disposableemailaddresses.com
@disposableinbox.com
@dispose.it
@dispostable.com
@divermail.com
@divismail.ru
@diwaq.com
@dlemail.ru
@dmarc.ro
@dndent.com
@dnses.ro
@dob.jp
@docmail.cz
@dodgeit.com
@dodgemail.de
@dodgit.com
@dodgit.org
@dodsi.com
@dolphinnet.net
@domainaing.gq
@domainaing.tk
@domforfb18.tk
@domforfb19.tk
@domforfb23.tk
@domforfb27.tk
@domforfb29.tk
@domforfb3.tk
@domforfb6.tk
@domforfb8.tk
@domozmail.com
@donemail.ru
@dontsendmespam.de
@dotmsg.com
@dp76.com
@dqnwara.com
@dr69.site
@drdrb.com
@drdrb.net
@dred.ru
@drevo.si
@drivetagdev.com
@dropcake.de
@dropmail.me
@duck2.club
@dumpandjunk.com
@dumpmail.de
@dumpyemail.com
@durandinterstellar.com
@dz17.net
@e-mail.com
@e-mail.igg.biz
@e-mail.org
@e-tomarigi.com
@e3z.de
@e4ward.com
@easy-trash-mail.com
@easynetwork.info
@easytrashmail.com
@eatmea2z.club
@eay.jp
@ebeschlussbuch.de
@ecolo-online.fr
@edgex.ru
@ee2.pl
@eelmail.com
@efxs.ca
@einmalmail.de
@einrot.com
@eintagsmail.de
@email-fake.com
@email-jetable.fr
@email-temp.com
@email60.com
@emailage.ml
@emailapps.info
@emailfake.ml
@emailfake.nut.cc
@emailfake.usa.cc
@emailgo.de
@emailigo.de
@emailinfive.com
@emaillime.com
@emailmiser.com
@emailna.co
@emailo.pro
@emailproxsy.com
@emailresort.com
@emailsecurer.com
@emailsensei.com
@emailsingularity.net
@emailtech.info
@emailtemporanea.com
@emailtemporario.com.br
@emailthe.net
@emailtmp.com
@emailto.de
@emailure.net
@emailwarden.com
@emailxfer.com
@emeil.in
@emeil.ir
@emeraldwebmail.com
@emil.com
@emlhub.com
@emlpro.com
@emltmp.com
@emz.net
@envy17.com
@ephemail.net
@ephemeral.email
@esc.la
@esemay.com
@ether123.net
@ethereum1.top
@ethersports.org
@ethersportz.info
@etlgr.com
@etranquil.com
@euaqa.com
@evilcomputer.com
@evyush.com
@express.net.ua
@extremail.ru
@eyepaste.com
@ezstest.com
@f1kzc0d3.tk
@f4k.es
@f5.si
@faecesmail.me
@fakeinbox.info
@fakemail.fr
@fakemailz.com
@fakemyinbox.com
@fangoh.com
@fantasymail.de
@fast-mail.fr
@fastkawasaki.com
@fastsuzuki.com
@fastyamaha.com
@fatflap.com
@fbmail.usa.cc
@fettometern.com
@fictionsite.com
@fightallspam.com
@figjs.com
@figshot.com
@film-blog.biz
@filzmail.com
@findu.pl
@fivemail.de
@fizmail.com
@fleckens.hu
@flemail.ru
@flowu.com
@flu-cc.flu.cc
@flucc.flu.cc
@fluidsoft.us
@flurred.com
@fly-ts.de
@flyinggeek.net
@foobarbot.net
@forecastertests.com
@forgetmail.com
@forspam.net
@forward.cat
@foxja.com
@foxtrotter.info
@fr.nf
@fr33mail.info
@frapmail.com
@freedom4you.info
@freefattymovies.com
@freeforall.site
@freelance-france.eu
@freeletter.me
@freemail.tweakly.net
@freemailzone.com
@freesistercam.com
@freundin.ru
@ftp.sh
@ftpinc.ca
@fuckedupload.com
@fuckme69.club
@fucknloveme.top
@fuckxxme.top
@fuirio.com
@fulvie.com
@fun64.com
@funnymail.de
@furusato.tokyo
@furzauflunge.de
@fuwamofu.com
@fxnxs.com
@fyii.de
@g14l71lb.com
@g1xmail.top
@g2xmail.top
@g3xmail.top
@gafy.net
@gaggle.net
@galaxy.tv
@gally.jp
@gamail.top
@gamgling.com
@garage46.com
@garasikita.pw
@garbagecollector.org
@garbagemail.org
@gardenscape.ca
@garizo.com
@garliclife.com
@garrymccooey.com
@gav0.com
@gbmail.top
@gcmail.top
@gdmail.top
@gedmail.win
@geekforex.com
@geew.ru
@geldwaschmaschine.de
@gelitik.in
@geludkita.tk
@genderfuck.net
@geronra.com
@get1mail.com
@get2mail.fr
@getairmail.com
@geteit.com
@getfun.men
@getmails.eu
@getnada.com
@getonemail.net
@giacmosuaviet.info
@giantmail.de
@gifto12.com
@ginzi.be
@girlmail.win
@girlsundertheinfluence.com
@gishpuppy.com
@givmail.com
@glubex.com
@glucosegrin.com
@gmatch.org
@gmx1mail.top
@gmxmail.top
@gmxmail.win
@go2usa.info
@go2vpn.net
@golemico.com
@gorillaswithdirtyarmpits.com
@goround.info
@gotimes.xyz
@gotmail.com
@gotmail.org
@grandmamail.com
@grandmasmail.com
@greenhousemail.com
@greensloth.com
@greggamel.com
@greggamel.net
@gregorygamel.com
@gregorygamel.net
@grish.de
@grr.la
@gsrv.co.uk
@guerillamail.info
@guerillamail.net
@guerillamailblock.com
@guerrillamail.biz
@guerrillamail.com
@guerrillamail.de
@guerrillamail.info
@guerrillamail.net
@guerrillamail.org
@guerrillamailblock.com
@gustr.com
@gxemail.men
@gynzy.eu
@gzb.ro
@h8s.org
@habitue.net
@hackthatbit.ch
@haida-edu.cn
@haltospam.com
@harakirimail.com
@haribu.com
@hartbot.de
@hat-geld.de
@hatespam.org
@haydoo.com
@hccmail.win
@headstrong.de
@heathenhammer.com
@hecat.es
@herpderp.nl
@hezll.com
@hi5.si
@hidebox.org
@hidemail.de
@hidzz.com
@hmail.us
@hmamail.com
@hoanggiaanh.com
@hoanglong.tech
@hochsitze.com
@hola.org
@honor-8.com
@hoo.com
@hopemail.biz
@hornyalwary.top
@hostlaba.com
@hot-mail.gq
@hotmai.com
@hotmessage.info
@hotmial.com
@hotpop.com
@housat.com
@hs.vc
@ht.cx
@hukkmu.tk
@hulapla.de
@hulksales.com
@humaility.com
@humn.ws.gy
@hvastudiesucces.nl
@i-phone.nut.cc
@iaoss.com
@ibsats.com
@ichigo.me
@icx.in
@ieatspam.info
@ieh-mail.de
@ige.es
@ignoremail.com
@iheartspam.org
@ikbenspamvrij.nl
@ilovespam.com
@imails.info
@imgof.com
@imgv.de
@imstations.com
@imul.info
@inboxalias.com
@inboxbear.com
@inboxclean.com
@inboxclean.org
@inboxdesign.me
@inboxed.pw
@inboxstore.me
@inclusiveprogress.com
@incq.com
@ind.st
@indirect.ws
@indoserver.stream
@infocom.zp.ua
@inoutmail.de
@instance-email.com
@instantblingmail.info
@instantemailaddress.com
@instantmail.fr
@intersteller.com
@iozak.com
@ip6.li
@ippandansei.tk
@irabops.com
@irish2me.com
@ironiebehindert.de
@isdaq.com
@isosq.com
@iuemail.men
@iwi.net
@ixx.io
@j-p.us
@j8k2.usa.cc
@jafps.com
@jamesbond.flu.cc
@jamesbond.igg.biz
@jamesbond.nut.cc
@jamesbond.usa.cc
@janproz.com
@jdmadventures.com
@jdz.ro
@jeie.igg.biz
@jellyrolls.com
@jetable.com
@jetable.fr.nf
@jetable.net
@jetable.org
@jilossesq.com
@jmail.ovh
@jobposts.net
@jobs-to-be-done.net
@joetestalot.com
@josse.ltd
@jourrapide.com
@jpco.org
@jsrsolutions.com
@junkmail.com
@juyouxi.com
@jwork.ru
@kademen.com
@kadokawa.tk
@kakadua.net
@kamsg.com
@katztube.com
@kazelink.ml
@kcrw.de
@keepmymail.com
@keipino.de
@kekita.com
@kennedy808.com
@kiani.com
@killmail.com
@kiois.com
@kismail.ru
@klassmaster.com
@klick-tipp.us
@klipschx12.com
@kloap.com
@kludgemush.com
@klzlk.com
@kmhow.com
@knol-power.nl
@kommunity.biz
@kopagas.com
@koszmail.pl
@ks87.igg.biz
@ks87.usa.cc
@kulturbetrieb.info
@kurzepost.de
@kwift.net
@kyal.pl
@lacedmail.com
@lackmail.net
@lackmail.ru
@lacto.info
@lags.us
@lain.ch
@lakelivingstonrealestate.com
@landmail.co
@laoeq.com
@last-chance.pro
@lastmail.co
@lazyinbox.com
@lazyinbox.us
@ldaho.net
@ldtp.com
@lee.mx
@leeching.net
@lenovog4.com
@letmeinonthis.com
@letthemeatspam.com
@level3.flu.cc
@level3.igg.biz
@level3.nut.cc
@level3.usa.cc
@lez.se
@lgxscreen.com
@lhsdv.com
@lifetimefriends.info
@lillemap.net
@link2mail.net
@lkgn.se
@llogin.ru
@loan101.pro
@loapq.com
@locanto1.club
@locantofuck.top
@locantowsite.club
@logular.com
@lol.ovpn.to
@lolfreak.net
@lookugly.com
@lordsofts.com
@lortemail.dk
@losemymail.com
@lovemeleaveme.com
@lr78.com
@lru.me
@luckymail.org
@lukecarriere.com
@lukop.dk
@lzoaq.com
@m4ilweb.info
@m5s.flu.cc
@m5s.igg.biz
@m5s.nut.cc
@maboard.com
@macr2.com
@mail-easy.fr
@mail-filter.com
@mail-temporaire.com
@mail-temporaire.fr
@mail.by
@mail.mezimages.net
@mail.qmeta.net
@mail114.net
@mail1a.de
@mail22.club
@mail2rss.org
@mail666.ru
@mail707.com
@mail72.com
@mailback.com
@mailbiz.biz
@mailblocks.com
@mailbox52.ga
@mailbox92.biz
@mailbucket.org
@mailcat.biz
@mailcatch.com
@mailde.de
@mailde.info
@maildrop.cc
@maildu.de
@maildx.com
@mailed.in
@mailed.ro
@maileimer.de
@maileme101.com
@mailexpire.com
@mailf5.com
@mailforspam.com
@mailfree.ml
@mailfs.com
@mailgov.info
@mailguard.me
@mailgutter.com
@mailhazard.com
@mailhazard.us
@mailhz.me
@mailin8r.com
@mailinater.com
@mailinator.co.uk
@mailinator.com
@mailinator.gq
@mailinator.info
@mailinator.net
@mailinator.org
@mailinator.usa.cc
@mailinator2.com
@mailincubator.com
@mailismagic.com
@mailmate.com
@mailme.lv
@mailme24.com
@mailmetrash.com
@mailmoat.com
@mailmoth.com
@mailms.com
@mailna.biz
@mailna.co
@mailna.in
@mailna.me
@mailnesia.com
@mailnull.com
@mailorg.org
@mailpick.biz
@mailproxsy.com
@mailquack.com
@mailrock.biz
@mailsac.com
@mailseal.de
@mailshell.com
@mailsiphon.com
@mailslapping.com
@mailsucker.net
@mailtechx.com
@mailtemp.info
@mailtemporaire.com
@mailtemporaire.fr
@mailtome.de
@mailtothis.com
@mailtraps.com
@mailtrash.net
@mailtrix.net
@mailtv.net
@mailtv.tv
@mailzi.ru
@mailzilla.com
@mainerfolg.info
@makemenaughty.club
@makemetheking.com
@malayalamdtp.com
@malove.site
@manifestgenerator.com
@mankyrecords.com
@mansiondev.com
@manybrain.com
@markmurfin.com
@masonline.info
@maswae.world
@matchpol.net
@mbx.cc
@mciek.com
@mdhc.tk
@mechanicalresumes.com
@mega.zik.dj
@meinspamschutz.de
@meltmail.com
@mendoanmail.club
@merry.pink
@messagebeamer.de
@mezimages.net
@mfsa.ru
@miaferrari.com
@midcoastcustoms.com
@midcoastcustoms.net
@midcoastsolutions.com
@midcoastsolutions.net
@mierdamail.com
@migmail.net
@migmail.pl
@mihep.com
@mijnhva.nl
@ministry-of-silly-walks.de
@mintemail.com
@misterpinball.de
@mji.ro
@ml8.ca
@mm5.se
@mnode.me
@moakt.co
@moakt.com
@moakt.ws
@mobileninja.co.uk
@mobilevpn.top
@moburl.com
@mockmyid.com
@moeri.org
@mohmal.com
@mohmal.im
@mohmal.in
@mohmal.tech
@monachat.tk
@moncourrier.fr.nf
@monemail.fr.nf
@monmail.fr.nf
@monumentmail.com
@moot.es
@moreawesomethanyou.com
@moreorcs.com
@morriesworld.ml
@morsin.com
@motique.de
@moza.pl
@mozej.com
@mp-j.igg.biz
@mp.igg.biz
@mr24.co
@msgos.com
@mspeciosa.com
@mswork.ru
@mt2009.com
@mt2015.com
@mtmdev.com
@muchomail.com
@mvrht.com
@mvrht.net
@mwarner.org
@my.safe-mail.gq
@my10minutemail.com
@mybitti.de
@mycleaninbox.net
@mycorneroftheinter.net
@mydemo.equipment
@myemailboxy.com
@myglockneronline.com
@myhagiasophia.com
@myindohome.services
@mymail-in.net
@mynetstore.de
@mypacks.net
@mypartyclip.de
@myspaceinc.com
@myspaceinc.org
@myspamless.com
@mystvpn.com
@mytandbergonline.com
@mytemp.email
@mytempemail.com
@mytrashmail.com
@myzx.com
@mziqo.com
@n1nja.org
@nabuma.com
@nada.email
@nada.ltd
@nakedtruth.biz
@nanonym.ch
@nbox.notif.me
@negated.com
@neko2.net
@neomailbox.com
@nepwk.com
@nervmich.net
@nervtmich.net
@netmails.net
@netricity.nl
@netris.net
@netzidiot.de
@neverbox.com
@nevermail.de
@newbpotato.tk
@newideasfornewpeople.info
@nezdiro.org
@nezzart.com
@nguyenusedcars.com
@nice-4u.com
@niepodam.pl
@nincsmail.com
@nincsmail.hu
@niwl.net
@nnh.com
@nnoway.ru
@nobugmail.com
@nobuma.com
@nomail.cf
@nomail.pw
@nomail.xl.cx
@nomail2me.com
@nonspam.eu
@nonspammer.de
@nonze.ro
@norseforce.com
@nospam.ze.tc
@nospam4.us
@nospamthanks.info
@nothingtoseehere.ca
@notmailinator.com
@notsharingmy.info
@nowhere.org
@nowmymail.com
@ntlhelp.net
@nullbox.info
@nurfuerspam.de
@nus.edu.sg
@nut-cc.nut.cc
@nutcc.nut.cc
@nutpa.net
@nwldx.com
@nwytg.com
@ny7.me
@nypato.com
@o2stk.org
@o7i.net
@obfusko.com
@objectmail.com
@obobbo.com
@obxpestcontrol.com
@odaymail.com
@odnorazovoe.ru
@oerpub.org
@offshore-proxies.net
@ohaaa.de
@okzk.com
@omail.pro
@omnievents.org
@one-time.email
@oneoffemail.com
@oneoffmail.com
@onewaymail.com
@onlatedotcom.info
@online.ms
@onlineidea.info
@onlysext.com
@oolus.com
@oopi.org
@opayq.com
@opendns.ro
@ordinaryamerican.net
@oroki.de
@otherinbox.com
@ourawesome.life
@ourpreviewdomain.com
@outmail.win
@ovi.usa.cc
@ovpn.to
@owlpic.com
@oxopoha.com
@p33.org
@p71ce1m.com
@pa9e.com
@pagamenti.tk
@paharpurmim.tk
@pancakemail.com
@paplease.com
@pastebitch.com
@pavilionx2.com
@payforclick.net
@payperex2.com
@pcmylife.com
@penoto.tk
@pepbot.com
@pfui.ru
@photo-impact.eu
@photomark.net
@pii.at
@piki.si
@pingir.com
@pisls.com
@pjjkp.com
@plexolan.de
@plhk.ru
@ploae.com
@plw.me
@pokemail.net
@politikerclub.de
@pooae.com
@pookmail.com
@popesodomy.com
@porsh.net
@posdz.com
@postonline.me
@poutineyourface.com
@powered.name
@ppetw.com
@predatorrat.tk
@premium-mail.fr
@primabananen.net
@privacy.net
@privatdemail.net
@privy-mail.com
@privy-mail.de
@privymail.de
@pro-tag.org
@procrackers.com
@projectcl.com
@propscore.com
@proxymail.eu
@prtnx.com
@psh.me
@psles.com
@puglieisi.com
@put2.net
@putthisinyourspamdatabase.com
@pw.mysafe.ml
@qaioz.com
@qasti.com
@qbfree.us
@qc.to
@qibl.at
@qiq.us
@qisdo.com
@qisoa.com
@qoika.com
@qq.com
@qsl.ro
@qtum-ico.com
@queuem.com
@quickinbox.com
@quickmail.nl
@ququb.com
@r4nd0m.de
@ra3.us
@rabin.ca
@raetp9.com
@raffles.gg
@raketenmann.de
@randomail.net
@rbb.org
@rcpt.at
@rdklcrv.xyz
@reality-concept.club
@reallymymail.com
@recipeforfailure.com
@recode.me
@reconmail.com
@recursor.net
@recyclemail.dk
@reddit.usa.cc
@redfeathercrow.com
@reftoken.net
@rejectmail.com
@reliable-mail.com
@remarkable.rocks
@remote.li
@reptilegenetics.com
@revolvingdoorhoax.org
@rhyta.com
@richfinances.pw
@riddermark.de
@rifkian.gq
@risingsuntouch.com
@rkomo.com
@rmqkr.net
@rnailinator.com
@ro.lt
@rollindo.agency
@ronnierage.net
@rootfest.net
@rotaniliam.com
@rowe-solutions.com
@royal.net
@rppkn.com
@rtrtr.com
@rtskiya.xyz
@rudymail.ml
@ruru.be
@rustydoor.com
@s-s.flu.cc
@s-s.igg.biz
@s-s.nut.cc
@s-s.usa.cc
@s0ny.flu.cc
@s0ny.igg.biz
@s0ny.net
@s0ny.nut.cc
@s0ny.usa.cc
@sabrestlouis.com
@safe-mail.net
@safermail.info
@safersignup.de
@safetymail.info
@samsclass.info
@sandelf.de
@sanfinder.com
@sanstr.com
@sausen.com
@scay.net
@schachrol.com
@schafmail.de
@schmid.cf
@schrott-email.de
@sd3.in
@secretemail.de
@secure-box.info
@secure-mail.biz
@secure-mail.cc
@secured-link.net
@securemail.flu.cc
@securemail.igg.biz
@securemail.nut.cc
@securemail.usa.cc
@seekapps.com
@seekjobs4u.com
@selfdestructingmail.com
@selfdestructingmail.org
@semail.us
@send22u.info
@sendfree.org
@sendingspecialflyers.com
@sendspamhere.com
@senseless-entertainment.com
@server.ms
@services391.com
@sexyalwasmi.top
@shalar.net
@sharedmailbox.org
@sharklasers.com
@shieldemail.com
@shiftmail.com
@shitmail.de
@shitmail.me
@shitmail.org
@shitware.nl
@shortmail.net
@shotmail.ru
@showslow.de
@shrib.com
@shut.name
@shut.ws
@sibmail.com
@sin.cl
@sinnlos-mail.de
@sino.tw
@siteposter.net
@sizzlemctwizzle.com
@skeefmail.com
@slave-auctions.net
@slippery.email
@slipry.net
@slothmail.net
@slushmail.com
@smallker.tk
@smashmail.de
@smellfear.com
@smellypotato.tk
@smtp99.com
@sneakemail.com
@sneakmail.de
@socrazy.club
@socrazy.online
@sofimail.com
@sofort-mail.de
@sofortmail.de
@sogetthis.com
@sohu.com
@soisz.com
@solar-impact.pro
@solvemail.info
@sonshi.cf
@soodmail.com
@soodomail.com
@spam4.me
@spamail.de
@spamarrest.com
@spamavert.com
@spambob.com
@spambog.com
@spambog.de
@spambog.net
@spambog.ru
@spambooger.com
@spambox.org
@spambox.us
@spamcannon.com
@spamcannon.net
@spamcon.org
@spamcorptastic.com
@spamcowboy.com
@spamcowboy.net
@spamcowboy.org
@spamday.com
@spamdecoy.net
@spamex.com
@spamfree.eu
@spamfree24.de
@spamfree24.eu
@spamfree24.info
@spamfree24.org
@spamhereplease.com
@spamify.com
@spaml.com
@spaml.de
@spammotel.com
@spamobox.com
@spamslicer.com
@spamstack.net
@spamthis.co.uk
@spamtrap.ro
@spamtroll.net
@spamwc.ga
@speed.1s.fr
@spoofmail.de
@spr.io
@spybox.de
@sroff.com
@ssoia.com
@stanfordujjain.com
@starlight-breaker.net
@startfu.com
@startkeys.com
@statdvr.com
@stathost.net
@stelliteop.info
@stinkefinger.net
@stop-my-spam.com
@storiqax.com
@storiqax.top
@storj99.com
@storj99.top
@stromox.com
@stuckmail.com
@stuffmail.de
@sudolife.me
@sudolife.net
@sudomail.biz
@sudomail.com
@sudomail.net
@sudoverse.com
@sudoverse.net
@sudoweb.net
@sudoworld.com
@sudoworld.net
@suhuempek.ga
@suoox.com
@super-auswahl.de
@supermailer.jp
@superplatyna.com
@superrito.com
@suremail.info
@svk.jp
@svxr.org
@sweetxxx.de
@swift10minutemail.com
@szerz.com
@tafmail.com
@tagyourself.com
@tahutex.online
@tanukis.org
@tapchicuoihoi.com
@taphear.com
@techemail.com
@techgroup.me
@teewars.org
@telecomix.pl
@teleworm.com
@teleworm.us
@tellos.xyz
@temp-mail.de
@temp-mail.org
@temp-mail.ru
@temp-mails.com
@tempail.com
@tempe-mail.com
@tempemail.biz
@tempemail.co.za
@tempemail.net
@tempinbox.co.uk
@tempinbox.com
@tempmail.co
@tempmail.de
@tempmail.it
@tempmail.us
@tempmailaddress.com
@tempmaildemo.com
@tempmailer.com
@tempmailer.de
@temporarioemail.com.br
@temporaryemail.us
@temporarymailaddress.com
@tempr.email
@tempthe.net
@tempymail.com
@testore.co
@thankyou2010.com
@thatim.info
@thc.st
@thediamants.org
@thedirhq.info
@thelimestones.com
@thex.ro
@thietbivanphong.asia
@thisisnotmyrealemail.com
@thnikka.com
@thraml.com
@thrma.com
@throam.com
@thrott.com
@throwam.com
@throwawayemailaddress.com
@throwawaymail.com
@throya.com
@thunkinator.org
@thxmate.com
@ti.igg.biz
@tiapz.com
@tic.ec
@tilien.com
@tinoza.org
@tiv.cc
@tizi.com
@tm2mail.com
@tmail.ws
@tmailinator.com
@tmails.net
@tmpeml.info
@tmpjr.me
@tmpmail.net
@tmpmail.org
@toddsbighug.com
@tokenmail.de
@tonymanso.com
@toomail.biz
@top1mail.ru
@top1post.ru
@toppieter.com
@topranklist.de
@toprumours.com
@toss.pw
@tosunkaya.com
@totalvista.com
@totoan.info
@tqoai.com
@tradermail.info
@tranceversal.com
@trash-amil.com
@trash-mail.at
@trash-mail.ml
@trash-me.com
@trash2009.com
@trashdevil.com
@trashemails.de
@trashinbox.com
@trashmail.at
@trashmail.com
@trashmail.de
@trashmail.io
@trashmail.me
@trashmail.net
@trashmail.org
@trashmailer.com
@trashmails.com
@trashymail.com
@trashymail.net
@trbvm.com
@trbvn.com
@trbvo.com
@trialmail.de
@trickmail.net
@trillianpro.com
@trollproject.com
@tryalert.com
@ttszuo.xyz
@tualias.com
@tuongtactot.tk
@turoid.com
@tuyulmokad.tk
@tvchd.com
@twinmail.de
@twocowmail.net
@txpwg.usa.cc
@txt.flu.cc
@tyhe.ro
@tyldd.com
@uacro.com
@ubismail.net
@ubm.md
@uemail99.com
@uggsrock.com
@ugimail.net
@uhhu.ru
@uiu.us
@uk.to
@unids.com
@urfunktion.se
@uroid.com
@us.af
@us.to
@usa-cc.usa.cc
@usako.net
@uscaves.com
@used-product.fr
@ushijima1129.tk
@uu.gl
@uwork4.us
@valemail.net
@vankin.de
@vctel.com
@vda.ro
@vektik.com
@vemomail.win
@venompen.com
@veo.kr
@ver0.tk
@verdejo.com
@veryday.ch
@veryday.eu
@veryday.info
@veryrealemail.com
@vfemail.net
@via.tokyo.jp
@viditag.com
@viewcastmedia.com
@vikingsonly.com
@vinernet.com
@vipepe.com
@vipmail.name
@vipmail.pw
@viralplays.com
@visal007.tk
@visal168.tk
@vkcode.ru
@vmani.com
@vmpanda.com
@vnedu.me
@voidbay.com
@vomoto.com
@vorga.org
@vpn.st
@vps30.com
@vps911.net
@vpstraffic.com
@vrmtr.com
@vsimcard.com
@vssms.com
@vtxmail.us
@vuiy.pw
@w3internet.co.uk
@walala.org
@walkmail.net
@walkmail.ru
@wallm.com
@wasteland.rfc822.org
@watchever.biz
@wazabi.club
@wbml.net
@web-ideal.fr
@web2mailco.com
@webcontact-france.eu
@webemail.me
@webmail.igg.biz
@webtrip.ch
@webuser.in
@wee.my
@wefjo.grn.cc
@weg-werf-email.de
@wegwerf-emails.de
@wegwerfadresse.de
@wegwerfemail.com
@wegwerfemail.info
@wegwerfemail.net
@wegwerfemail.org
@wegwerfmail.de
@wegwerfmail.info
@wegwerfmail.net
@wegwerfmail.org
@wegwerpmailadres.nl
@wegwrfmail.net
@wegwrfmail.org
@wg0.com
@whatifanalytics.com
@wickmail.net
@wierie.tk
@wikidocuslava.ru
@wilemail.com
@willselfdestruct.com
@wimsg.com
@wins.com.br
@wolfsmail.tk
@wollan.info
@writeme.us
@wronghead.com
@wudet.men
@wuespdj.xyz
@wupics.com
@wuzupmail.net
@www.e4ward.com
@wwwnew.eu
@wxnw.net
@x24.com
@xbaby69.top
@xcode.ro
@xcpy.com
@xemaps.com
@xemne.com
@xents.com
@xjoi.com
@xl.cx
@xmail.com
@xmaily.com
@xn--9kq967o.com
@xost.us
@xoxy.net
@xperiae5.com
@xrho.com
@xww.ro
@xxi2.com
@xxlocanto.us
@xxolocanto.us
@xxqx3802.com
@yabai-oppai.tk
@yahmail.top
@yamail.win
@yannmail.win
@ycare.de
@ycn.ro
@ye.vc
@yedi.org
@yodx.ro
@yomail.info
@yopmail.com
@yopmail.fr
@yopmail.net
@yopmail.usa.cc
@yougotgoated.com
@yourdomain.com
@yourlms.biz
@yspend.com
@yueluqu.cn
@yugasandrika.com
@yui.it
@yuurok.com
@yxzx.net
@z0d.eu
@z1p.biz
@z86.ru
@zain.site
@zainmax.net
@zaktouni.fr
@zasod.com
@zebins.com
@zebins.eu
@zehnminutenmail.de
@zepp.dk
@zetmail.com
@zfymail.com
@zhcne.com
@zhewei88.com
@zhorachu.com
@zik.dj
@zipcad.com
@zippymail.info
@zoemail.com
@zoemail.net
@zomg.info
@zoqqa.com
@zxcvbnm.com
@zzz.com`;

const list = masks.split('\n').filter(Boolean);

export default list;
